services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=your_mongodb_uri_here
      - JWT_SECRET=dbhshdhsdhvshvhvhfs
      - PORT=3000
    # depends_on:
    #   - mongo
    restart: unless-stopped
    networks:
      - app-network

#   mongo:
#     image: mongo:7.0
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       - MONGO_INITDB_DATABASE=myapp
#     restart: unless-stopped
#     networks:
#       - app-network

# volumes:
#   mongo-data:

networks:
  app-network:
    driver: bridge
